### ISSUE TITLE
Add license for code

### ISSUE THREAD

**Issue by Hocdoc** [joshuawootonn/react-components-from-scratch#2]
I really like the blog series very much, the code is very clean and the components are accessible. :-)

Could you please add a license to your code (f.ex. in this GitHub repository), so I know if I'm allowed to reuse most parts of your perfect code?

**Comment by joshuawootonn** [comment]
Hi there. I am sorry for taking so long to reply. I need to get better at managing notifications!

Feel free to use any of the components I have created!

**Comment by joshuawootonn** [comment]
I added a license BTW!
